# Generated by Django 2.0.6 on 2018-06-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.SmallIntegerField()),
                ('usr_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usr_fecha_edicion', models.DateTimeField(auto_now=True)),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
