# Generated by Django 2.0.6 on 2018-06-10 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomProfessionalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesional_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional.ProfessionalService')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('ubigeo', models.CharField(max_length=6)),
                ('professionalservices', models.ManyToManyField(through='rooms.RoomProfessionalService', to='professional.ProfessionalService')),
            ],
        ),
        migrations.AddField(
            model_name='roomprofessionalservice',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Rooms'),
        ),
    ]
