# Generated by Django 2.0.6 on 2018-06-10 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.SmallIntegerField()),
                ('usr_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usr_fecha_edicion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessionalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professional.Professional')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.Services')),
            ],
        ),
        migrations.AddField(
            model_name='professional',
            name='services',
            field=models.ManyToManyField(through='professional.ProfessionalService', to='services.Services'),
        ),
    ]
