# Generated by Django 2.0.6 on 2018-06-10 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20180610_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookings.BookingState'),
        ),
    ]
